language: "en-US"
early_access: true
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "Draft"
    labels:
      - "CodeRabbit"
  tools:
    ast-grep:
      enabled: true
      rule_dirs:
        - "custom-rules"
    linter:
      enabled: true
chat:
  auto_reply: true
