// <auto-generated />
using System;
using CRM.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crm")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRM.Domain.AutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("ActionTemplateId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ParameterJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerDelayMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Trigger", "IsActive")
                        .HasDatabaseName("ix_automation_rules_trigger_active");

                    b.ToTable("AutomationRules", "crm");
                });

            modelBuilder.Entity("CRM.Domain.CustomerAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageOrderValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("EmailClickCount")
                        .HasColumnType("integer");

                    b.Property<int>("EmailOpenCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstPurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FrequencyScore")
                        .HasColumnType("integer");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastEmailOpenedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastInteractionAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastPurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastRfmCalculatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LifecycleStage")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LifecycleStageChangedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MonetaryScore")
                        .HasColumnType("integer");

                    b.Property<int>("RecencyScore")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOrderCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LastPurchaseDate")
                        .HasDatabaseName("ix_customer_analytics_last_purchase");

                    b.HasIndex("LifecycleStage")
                        .HasDatabaseName("ix_customer_analytics_lifecycle_stage");

                    b.HasIndex("TotalSpent")
                        .HasDatabaseName("ix_customer_analytics_total_spent");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_customer_analytics_user_id");

                    b.HasIndex("RecencyScore", "FrequencyScore", "MonetaryScore")
                        .HasDatabaseName("ix_customer_analytics_rfm_scores");

                    b.ToTable("CustomerAnalytics", "crm");
                });

            modelBuilder.Entity("CRM.Domain.CustomerInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attachments")
                        .HasColumnType("jsonb");

                    b.Property<string>("CallOutcome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("CustomerAnalyticsId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FollowUpNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("MeetingLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PerformedByUserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sentiment")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAnalyticsId")
                        .HasDatabaseName("ix_interactions_customer");

                    b.HasIndex("FollowUpDate")
                        .HasDatabaseName("ix_interactions_follow_up");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_interactions_lead");

                    b.HasIndex("PerformedAt")
                        .HasDatabaseName("ix_interactions_performed_at");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_interactions_type");

                    b.ToTable("CustomerInteractions", "crm");
                });

            modelBuilder.Entity("CRM.Domain.CustomerSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("CustomerCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAutoAssign")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RuleDefinition")
                        .HasColumnType("jsonb");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_customer_segments_code");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_customer_segments_sort_order");

                    b.ToTable("CustomerSegments", "crm");
                });

            modelBuilder.Entity("CRM.Domain.CustomerSegmentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerAnalyticsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAutoAssigned")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SegmentId");

                    b.HasIndex("CustomerAnalyticsId", "SegmentId")
                        .IsUnique()
                        .HasDatabaseName("uq_segment_assignments_customer_segment");

                    b.ToTable("CustomerSegmentAssignments", "crm");
                });

            modelBuilder.Entity("CRM.Domain.CustomerTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedToUserName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("CustomerAnalyticsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReminderAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_tasks_assigned_to");

                    b.HasIndex("CustomerAnalyticsId");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_tasks_due_date");

                    b.HasIndex("LeadId");

                    b.HasIndex("ReminderAt")
                        .HasDatabaseName("ix_tasks_pending_reminders")
                        .HasFilter("\"ReminderSent\" = false");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tasks_status");

                    b.ToTable("CustomerTasks", "crm");
                });

            modelBuilder.Entity("CRM.Domain.EmailCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BouncedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ClickedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DeliveredCount")
                        .HasColumnType("integer");

                    b.Property<string>("FromEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FromName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MinRfmScore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OpenedCount")
                        .HasColumnType("integer");

                    b.Property<string>("PlainTextContent")
                        .HasColumnType("text");

                    b.Property<string>("PreviewText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReplyToEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SentCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TargetLifecycleStages")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("TargetSegmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalRecipients")
                        .HasColumnType("integer");

                    b.Property<int>("UnsubscribedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("ix_campaigns_scheduled_at");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("ix_campaigns_sent_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_campaigns_status");

                    b.HasIndex("TargetSegmentId");

                    b.ToTable("EmailCampaigns", "crm");
                });

            modelBuilder.Entity("CRM.Domain.EmailCampaignRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BounceReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("BouncedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClickedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ClickedLinks")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("CustomerAnalyticsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("OpenCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TrackingId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UnsubscribedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAnalyticsId");

                    b.HasIndex("TrackingId")
                        .IsUnique()
                        .HasDatabaseName("uq_recipients_tracking_id");

                    b.HasIndex("CampaignId", "Email")
                        .IsUnique()
                        .HasDatabaseName("uq_recipients_campaign_email");

                    b.HasIndex("CampaignId", "Status")
                        .HasDatabaseName("ix_email_campaign_recipients_campaign_id_status");

                    b.ToTable("EmailCampaignRecipients", "crm");
                });

            modelBuilder.Entity("CRM.Domain.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedToUserName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ConvertedCustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("EstimatedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InterestedProducts")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConverted")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LossReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("NextFollowUpAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NextFollowUpNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("PipelineStageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceDetail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_leads_assigned_to");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_leads_created_at");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_leads_email");

                    b.HasIndex("NextFollowUpAt")
                        .HasDatabaseName("ix_leads_next_follow_up");

                    b.HasIndex("PipelineStageId");

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_leads_source");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_leads_status");

                    b.ToTable("Leads", "crm");
                });

            modelBuilder.Entity("CRM.Domain.LeadPipelineStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinalStage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWonStage")
                        .HasColumnType("boolean");

                    b.Property<int>("LeadCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalEstimatedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("WinProbability")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_pipeline_stages_sort_order");

                    b.ToTable("LeadPipelineStages", "crm");
                });

            modelBuilder.Entity("CRM.Domain.CustomerInteraction", b =>
                {
                    b.HasOne("CRM.Domain.CustomerAnalytics", "CustomerAnalytics")
                        .WithMany()
                        .HasForeignKey("CustomerAnalyticsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_interactions_customer");

                    b.HasOne("CRM.Domain.Lead", "Lead")
                        .WithMany("Interactions")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_interactions_lead");

                    b.Navigation("CustomerAnalytics");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("CRM.Domain.CustomerSegmentAssignment", b =>
                {
                    b.HasOne("CRM.Domain.CustomerAnalytics", "CustomerAnalytics")
                        .WithMany()
                        .HasForeignKey("CustomerAnalyticsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_segment_assignments_customer");

                    b.HasOne("CRM.Domain.CustomerSegment", "Segment")
                        .WithMany("Assignments")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_segment_assignments_segment");

                    b.Navigation("CustomerAnalytics");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("CRM.Domain.CustomerTask", b =>
                {
                    b.HasOne("CRM.Domain.CustomerAnalytics", "CustomerAnalytics")
                        .WithMany()
                        .HasForeignKey("CustomerAnalyticsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tasks_customer");

                    b.HasOne("CRM.Domain.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tasks_lead");

                    b.Navigation("CustomerAnalytics");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("CRM.Domain.EmailCampaign", b =>
                {
                    b.HasOne("CRM.Domain.CustomerSegment", "TargetSegment")
                        .WithMany()
                        .HasForeignKey("TargetSegmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_campaigns_target_segment");

                    b.Navigation("TargetSegment");
                });

            modelBuilder.Entity("CRM.Domain.EmailCampaignRecipient", b =>
                {
                    b.HasOne("CRM.Domain.EmailCampaign", "Campaign")
                        .WithMany("Recipients")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipients_campaign");

                    b.HasOne("CRM.Domain.CustomerAnalytics", "CustomerAnalytics")
                        .WithMany()
                        .HasForeignKey("CustomerAnalyticsId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recipients_customer");

                    b.Navigation("Campaign");

                    b.Navigation("CustomerAnalytics");
                });

            modelBuilder.Entity("CRM.Domain.Lead", b =>
                {
                    b.HasOne("CRM.Domain.LeadPipelineStage", "PipelineStage")
                        .WithMany("Leads")
                        .HasForeignKey("PipelineStageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_leads_pipeline_stage");

                    b.Navigation("PipelineStage");
                });

            modelBuilder.Entity("CRM.Domain.CustomerSegment", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("CRM.Domain.EmailCampaign", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("CRM.Domain.Lead", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("CRM.Domain.LeadPipelineStage", b =>
                {
                    b.Navigation("Leads");
                });
#pragma warning restore 612, 618
        }
    }
}
