// GENERATED FILE - do not hand-edit.
// Source: plans/260917-2100-full-system-overhaul/reports/w1-1-permissions.json
// (W1-1 permission catalog, seedVersion 2). Regenerate from that JSON
// if the backend catalog changes - see phase-17-w1-fe-app-shell.md Risk Assessment:
// "import permission strings from a generated constants/permissions.ts; do not hand-type."

export type PermissionActionType =
  'Approve' | 'Create' | 'Delete' | 'Edit' | 'Export' | 'Manage' | 'View';

export interface PermissionCatalogEntry {
  key: string;
  module: string;
  moduleDisplayName: string;
  displayName: string;
  type: PermissionActionType;
  dependsOn: string | null;
  roles: readonly string[];
}

export const PERMISSIONS_CATALOG: readonly PermissionCatalogEntry[] = [
  { key: 'Permissions.Catalog.View', module: 'Catalog', moduleDisplayName: 'Sản phẩm', displayName: 'Xem danh sách sản phẩm', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale', 'InventoryStaff', 'Marketing', 'TechnicianInShop', 'TechnicianOnSite', 'Customer', 'Supplier'] },
  { key: 'Permissions.Catalog.Create', module: 'Catalog', moduleDisplayName: 'Sản phẩm', displayName: 'Thêm sản phẩm mới', type: 'Create', dependsOn: 'Permissions.Catalog.View', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Catalog.Edit', module: 'Catalog', moduleDisplayName: 'Sản phẩm', displayName: 'Chỉnh sửa sản phẩm', type: 'Edit', dependsOn: 'Permissions.Catalog.View', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Catalog.Delete', module: 'Catalog', moduleDisplayName: 'Sản phẩm', displayName: 'Xoá sản phẩm', type: 'Delete', dependsOn: 'Permissions.Catalog.View', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Catalog.Manage', module: 'Catalog', moduleDisplayName: 'Sản phẩm', displayName: 'Quản lý danh mục, thương hiệu, thuộc tính', type: 'Manage', dependsOn: 'Permissions.Catalog.View', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Catalog.Export', module: 'Catalog', moduleDisplayName: 'Sản phẩm', displayName: 'Xuất file danh sách sản phẩm', type: 'Export', dependsOn: 'Permissions.Catalog.View', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Catalog.Import', module: 'Catalog', moduleDisplayName: 'Sản phẩm', displayName: 'Nhập sản phẩm hàng loạt từ file', type: 'Create', dependsOn: 'Permissions.Catalog.Create', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Catalog.BulkPrice', module: 'Catalog', moduleDisplayName: 'Sản phẩm', displayName: 'Đổi giá hàng loạt', type: 'Edit', dependsOn: 'Permissions.Catalog.Edit', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Sales.ViewOwn', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Xem đơn hàng của chính mình', type: 'View', dependsOn: null, roles: ['Admin', 'Customer'] },
  { key: 'Permissions.Sales.ViewAll', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Xem tất cả đơn hàng', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale', 'Accountant', 'Marketing'] },
  { key: 'Permissions.Sales.ManageAll', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Sửa mọi đơn hàng', type: 'Manage', dependsOn: 'Permissions.Sales.ViewAll', roles: ['Admin', 'Manager', 'Sale'] },
  { key: 'Permissions.Sales.Checkout', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Đặt hàng / thanh toán', type: 'Create', dependsOn: null, roles: ['Admin', 'Sale', 'Customer'] },
  { key: 'Permissions.Sales.UpdateStatus', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Cập nhật trạng thái đơn', type: 'Edit', dependsOn: 'Permissions.Sales.ViewAll', roles: ['Admin', 'Manager', 'Sale'] },
  { key: 'Permissions.Sales.CancelOrder', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Huỷ đơn hàng', type: 'Delete', dependsOn: 'Permissions.Sales.ViewAll', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Sales.ViewReturns', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Xem yêu cầu đổi/trả', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale'] },
  { key: 'Permissions.Sales.ManageReturns', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Xử lý đổi/trả hàng', type: 'Manage', dependsOn: 'Permissions.Sales.ViewReturns', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Sales.Pos', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Bán hàng tại quầy (POS)', type: 'Create', dependsOn: 'Permissions.Sales.ViewAll', roles: ['Admin', 'Manager', 'Sale'] },
  { key: 'Permissions.Sales.Export', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Xuất báo cáo bán hàng', type: 'Export', dependsOn: 'Permissions.Sales.ViewAll', roles: ['Admin', 'Manager', 'Sale'] },
  { key: 'Permissions.Sales.SellOnCredit', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Bán công nợ (ghi nợ khách)', type: 'Approve', dependsOn: 'Permissions.Sales.ViewAll', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Sales.TakeDeposit', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Nhận đặt cọc', type: 'Create', dependsOn: 'Permissions.Sales.ViewAll', roles: ['Admin', 'Manager', 'Sale'] },
  { key: 'Permissions.Sales.ManageInstallments', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Quản lý trả góp', type: 'Manage', dependsOn: 'Permissions.Sales.ViewAll', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Sales.Quotations.View', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Xem báo giá', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale'] },
  { key: 'Permissions.Sales.Quotations.Create', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Tạo báo giá', type: 'Create', dependsOn: 'Permissions.Sales.Quotations.View', roles: ['Admin', 'Manager', 'Sale'] },
  { key: 'Permissions.Sales.Quotations.Edit', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Sửa báo giá', type: 'Edit', dependsOn: 'Permissions.Sales.Quotations.View', roles: ['Admin', 'Manager', 'Sale'] },
  { key: 'Permissions.Sales.Quotations.Approve', module: 'Sales', moduleDisplayName: 'Bán hàng', displayName: 'Duyệt báo giá', type: 'Approve', dependsOn: 'Permissions.Sales.Quotations.View', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Inventory.ViewStock', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Xem tồn kho', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale', 'InventoryStaff', 'Accountant', 'TechnicianInShop', 'TechnicianOnSite'] },
  { key: 'Permissions.Inventory.ManageStock', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Nhập/xuất kho', type: 'Manage', dependsOn: 'Permissions.Inventory.ViewStock', roles: ['Admin', 'Manager', 'InventoryStaff'] },
  { key: 'Permissions.Inventory.AdjustStock', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Điều chỉnh tồn kho, kiểm kê', type: 'Edit', dependsOn: 'Permissions.Inventory.ViewStock', roles: ['Admin', 'Manager', 'InventoryStaff'] },
  { key: 'Permissions.Inventory.ViewSupplier', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Xem nhà cung cấp', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'InventoryStaff', 'Accountant'] },
  { key: 'Permissions.Inventory.CreateSupplier', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Thêm nhà cung cấp', type: 'Create', dependsOn: 'Permissions.Inventory.ViewSupplier', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Inventory.UpdateSupplier', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Sửa nhà cung cấp', type: 'Edit', dependsOn: 'Permissions.Inventory.ViewSupplier', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Inventory.DeleteSupplier', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Xoá nhà cung cấp', type: 'Delete', dependsOn: 'Permissions.Inventory.ViewSupplier', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Inventory.ViewPurchaseOrder', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Xem đơn mua hàng', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'InventoryStaff', 'Accountant', 'Supplier'] },
  { key: 'Permissions.Inventory.CreatePurchaseOrder', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Tạo đơn mua / đề nghị mua', type: 'Create', dependsOn: 'Permissions.Inventory.ViewPurchaseOrder', roles: ['Admin', 'Manager', 'InventoryStaff'] },
  { key: 'Permissions.Inventory.ApprovePurchaseOrder', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Duyệt đơn mua hàng', type: 'Approve', dependsOn: 'Permissions.Inventory.ViewPurchaseOrder', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Inventory.ReceivePurchaseOrder', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Nhận hàng nhập kho (GRN)', type: 'Manage', dependsOn: 'Permissions.Inventory.ViewPurchaseOrder', roles: ['Admin', 'Manager', 'InventoryStaff'] },
  { key: 'Permissions.Inventory.ViewReservations', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Xem hàng giữ chỗ', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'InventoryStaff', 'TechnicianInShop'] },
  { key: 'Permissions.Inventory.Approve', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Duyệt nghiệp vụ kho (gồm chuyển kho một bước)', type: 'Approve', dependsOn: 'Permissions.Inventory.ViewStock', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Inventory.ImportOpening', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Nhập tồn đầu kỳ', type: 'Create', dependsOn: 'Permissions.Inventory.ManageStock', roles: ['Admin', 'Manager', 'InventoryStaff'] },
  { key: 'Permissions.Inventory.QuickReceive', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Nhập nhanh không cần đơn mua', type: 'Create', dependsOn: 'Permissions.Inventory.ManageStock', roles: ['Admin', 'Manager', 'InventoryStaff'] },
  { key: 'Permissions.Inventory.Export', module: 'Inventory', moduleDisplayName: 'Kho', displayName: 'Xuất báo cáo kho', type: 'Export', dependsOn: 'Permissions.Inventory.ViewStock', roles: ['Admin', 'Manager', 'InventoryStaff'] },
  { key: 'Permissions.Payments.View', module: 'Payments', moduleDisplayName: 'Thanh toán', displayName: 'Xem giao dịch thanh toán', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale', 'Accountant'] },
  { key: 'Permissions.Payments.Reconcile', module: 'Payments', moduleDisplayName: 'Thanh toán', displayName: 'Đối soát sao kê ngân hàng', type: 'Manage', dependsOn: 'Permissions.Payments.View', roles: ['Admin', 'Manager', 'Accountant'] },
  { key: 'Permissions.Payments.Refund', module: 'Payments', moduleDisplayName: 'Thanh toán', displayName: 'Hoàn tiền', type: 'Approve', dependsOn: 'Permissions.Payments.View', roles: ['Admin', 'Manager', 'Accountant'] },
  { key: 'Permissions.Payments.CollectCod', module: 'Payments', moduleDisplayName: 'Thanh toán', displayName: 'Xác nhận thu COD', type: 'Manage', dependsOn: 'Permissions.Payments.View', roles: ['Admin', 'Manager', 'Sale', 'Accountant'] },
  { key: 'Permissions.Payments.Configure', module: 'Payments', moduleDisplayName: 'Thanh toán', displayName: 'Cấu hình cổng thanh toán', type: 'Manage', dependsOn: 'Permissions.Payments.View', roles: ['Admin'] },
  { key: 'Permissions.Repair.Book', module: 'Repair', moduleDisplayName: 'Sửa chữa', displayName: 'Đặt lịch sửa chữa', type: 'Create', dependsOn: null, roles: ['Admin', 'Sale', 'Customer'] },
  { key: 'Permissions.Repair.ViewOwn', module: 'Repair', moduleDisplayName: 'Sửa chữa', displayName: 'Xem phiếu sửa chữa của mình', type: 'View', dependsOn: null, roles: ['Admin', 'TechnicianInShop', 'TechnicianOnSite', 'Customer'] },
  { key: 'Permissions.Repair.ViewAll', module: 'Repair', moduleDisplayName: 'Sửa chữa', displayName: 'Xem tất cả phiếu sửa chữa', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale', 'TechnicianInShop', 'TechnicianOnSite'] },
  { key: 'Permissions.Repair.UpdateStatus', module: 'Repair', moduleDisplayName: 'Sửa chữa', displayName: 'Cập nhật tiến độ sửa chữa', type: 'Edit', dependsOn: 'Permissions.Repair.ViewAll', roles: ['Admin', 'Manager', 'TechnicianInShop', 'TechnicianOnSite'] },
  { key: 'Permissions.Repair.AssignTechnician', module: 'Repair', moduleDisplayName: 'Sửa chữa', displayName: 'Phân công kỹ thuật viên', type: 'Manage', dependsOn: 'Permissions.Repair.ViewAll', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Repair.CreateQuote', module: 'Repair', moduleDisplayName: 'Sửa chữa', displayName: 'Lập báo giá sửa chữa', type: 'Create', dependsOn: 'Permissions.Repair.ViewAll', roles: ['Admin', 'Manager', 'TechnicianInShop', 'TechnicianOnSite'] },
  { key: 'Permissions.Repair.ApproveQuote', module: 'Repair', moduleDisplayName: 'Sửa chữa', displayName: 'Duyệt báo giá sửa chữa', type: 'Approve', dependsOn: 'Permissions.Repair.ViewAll', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Repair.Complete', module: 'Repair', moduleDisplayName: 'Sửa chữa', displayName: 'Hoàn tất phiếu sửa chữa', type: 'Manage', dependsOn: 'Permissions.Repair.ViewAll', roles: ['Admin', 'Manager', 'TechnicianInShop', 'TechnicianOnSite'] },
  { key: 'Permissions.Warranty.SubmitClaim', module: 'Warranty', moduleDisplayName: 'Bảo hành', displayName: 'Gửi yêu cầu bảo hành', type: 'Create', dependsOn: null, roles: ['Admin', 'Sale', 'Customer'] },
  { key: 'Permissions.Warranty.ViewOwn', module: 'Warranty', moduleDisplayName: 'Bảo hành', displayName: 'Xem yêu cầu bảo hành của mình', type: 'View', dependsOn: null, roles: ['Admin', 'TechnicianOnSite', 'Customer'] },
  { key: 'Permissions.Warranty.ViewAll', module: 'Warranty', moduleDisplayName: 'Bảo hành', displayName: 'Xem tất cả yêu cầu bảo hành', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale', 'TechnicianInShop', 'TechnicianOnSite'] },
  { key: 'Permissions.Warranty.ReviewClaim', module: 'Warranty', moduleDisplayName: 'Bảo hành', displayName: 'Xử lý yêu cầu bảo hành', type: 'Manage', dependsOn: 'Permissions.Warranty.ViewAll', roles: ['Admin', 'Manager', 'TechnicianInShop', 'TechnicianOnSite'] },
  { key: 'Permissions.Warranty.ApproveClaim', module: 'Warranty', moduleDisplayName: 'Bảo hành', displayName: 'Duyệt yêu cầu bảo hành', type: 'Approve', dependsOn: 'Permissions.Warranty.ViewAll', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Warranty.Moderate', module: 'Warranty', moduleDisplayName: 'Bảo hành', displayName: 'Kiểm duyệt nội dung khách gửi kèm', type: 'Manage', dependsOn: 'Permissions.Warranty.ViewAll', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Content.ViewPages', module: 'Content', moduleDisplayName: 'Nội dung', displayName: 'Xem trang tĩnh', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale', 'Marketing', 'Customer'] },
  { key: 'Permissions.Content.ManagePages', module: 'Content', moduleDisplayName: 'Nội dung', displayName: 'Quản lý trang tĩnh', type: 'Manage', dependsOn: 'Permissions.Content.ViewPages', roles: ['Admin', 'Manager', 'Marketing'] },
  { key: 'Permissions.Content.ViewPosts', module: 'Content', moduleDisplayName: 'Nội dung', displayName: 'Xem bài viết', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale', 'Marketing', 'Customer'] },
  { key: 'Permissions.Content.ManagePosts', module: 'Content', moduleDisplayName: 'Nội dung', displayName: 'Quản lý bài viết', type: 'Manage', dependsOn: 'Permissions.Content.ViewPosts', roles: ['Admin', 'Manager', 'Marketing'] },
  { key: 'Permissions.Content.ViewCoupons', module: 'Content', moduleDisplayName: 'Nội dung', displayName: 'Xem mã giảm giá', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale', 'Marketing'] },
  { key: 'Permissions.Content.ManageCoupons', module: 'Content', moduleDisplayName: 'Nội dung', displayName: 'Quản lý mã giảm giá, khuyến mãi', type: 'Manage', dependsOn: 'Permissions.Content.ViewCoupons', roles: ['Admin', 'Manager', 'Marketing'] },
  { key: 'Permissions.Content.ViewBanners', module: 'Content', moduleDisplayName: 'Nội dung', displayName: 'Xem banner', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Marketing'] },
  { key: 'Permissions.Content.ManageBanners', module: 'Content', moduleDisplayName: 'Nội dung', displayName: 'Quản lý banner trang chủ', type: 'Manage', dependsOn: 'Permissions.Content.ViewBanners', roles: ['Admin', 'Manager', 'Marketing'] },
  { key: 'Permissions.Content.ManageMedia', module: 'Content', moduleDisplayName: 'Nội dung', displayName: 'Tải lên và quản lý thư viện ảnh', type: 'Manage', dependsOn: 'Permissions.Content.ViewPages', roles: ['Admin', 'Manager', 'Marketing'] },
  { key: 'Permissions.Content.ManageMenus', module: 'Content', moduleDisplayName: 'Nội dung', displayName: 'Quản lý menu điều hướng', type: 'Manage', dependsOn: 'Permissions.Content.ViewPages', roles: ['Admin', 'Manager', 'Marketing'] },
  { key: 'Permissions.Content.ManageContacts', module: 'Content', moduleDisplayName: 'Nội dung', displayName: 'Xử lý liên hệ từ website', type: 'Manage', dependsOn: 'Permissions.Content.ViewPages', roles: ['Admin', 'Manager', 'Marketing'] },
  { key: 'Permissions.CRM.ViewCustomers', module: 'CRM', moduleDisplayName: 'Khách hàng', displayName: 'Xem khách hàng', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale', 'Marketing'] },
  { key: 'Permissions.CRM.ManageCustomers', module: 'CRM', moduleDisplayName: 'Khách hàng', displayName: 'Sửa thông tin khách hàng', type: 'Manage', dependsOn: 'Permissions.CRM.ViewCustomers', roles: ['Admin', 'Manager', 'Sale'] },
  { key: 'Permissions.CRM.ViewLeads', module: 'CRM', moduleDisplayName: 'Khách hàng', displayName: 'Xem khách hàng tiềm năng', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale', 'Marketing'] },
  { key: 'Permissions.CRM.ManageLeads', module: 'CRM', moduleDisplayName: 'Khách hàng', displayName: 'Quản lý khách hàng tiềm năng', type: 'Manage', dependsOn: 'Permissions.CRM.ViewLeads', roles: ['Admin', 'Manager', 'Sale'] },
  { key: 'Permissions.CRM.ViewSegments', module: 'CRM', moduleDisplayName: 'Khách hàng', displayName: 'Xem tệp khách hàng', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale', 'Marketing'] },
  { key: 'Permissions.CRM.ManageSegments', module: 'CRM', moduleDisplayName: 'Khách hàng', displayName: 'Quản lý tệp khách hàng', type: 'Manage', dependsOn: 'Permissions.CRM.ViewSegments', roles: ['Admin', 'Manager', 'Marketing'] },
  { key: 'Permissions.CRM.ViewAnalytics', module: 'CRM', moduleDisplayName: 'Khách hàng', displayName: 'Xem phân tích khách hàng', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Marketing'] },
  { key: 'Permissions.CRM.ManageTasks', module: 'CRM', moduleDisplayName: 'Khách hàng', displayName: 'Quản lý công việc chăm sóc KH', type: 'Manage', dependsOn: 'Permissions.CRM.ViewCustomers', roles: ['Admin', 'Manager', 'Sale'] },
  { key: 'Permissions.CRM.ViewCampaigns', module: 'CRM', moduleDisplayName: 'Khách hàng', displayName: 'Xem chiến dịch marketing', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Marketing'] },
  { key: 'Permissions.CRM.ManageCampaigns', module: 'CRM', moduleDisplayName: 'Khách hàng', displayName: 'Soạn chiến dịch marketing', type: 'Manage', dependsOn: 'Permissions.CRM.ViewCampaigns', roles: ['Admin', 'Manager', 'Marketing'] },
  { key: 'Permissions.CRM.SendCampaigns', module: 'CRM', moduleDisplayName: 'Khách hàng', displayName: 'Gửi chiến dịch (email/SMS) thật', type: 'Approve', dependsOn: 'Permissions.CRM.ManageCampaigns', roles: ['Admin', 'Manager', 'Marketing'] },
  { key: 'Permissions.Accounting.ViewInvoices', module: 'Accounting', moduleDisplayName: 'Kế toán', displayName: 'Xem hoá đơn, sổ sách', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Accountant'] },
  { key: 'Permissions.Accounting.CreateInvoice', module: 'Accounting', moduleDisplayName: 'Kế toán', displayName: 'Tạo hoá đơn', type: 'Create', dependsOn: 'Permissions.Accounting.ViewInvoices', roles: ['Admin', 'Manager', 'Accountant'] },
  { key: 'Permissions.Accounting.EditInvoice', module: 'Accounting', moduleDisplayName: 'Kế toán', displayName: 'Sửa hoá đơn', type: 'Edit', dependsOn: 'Permissions.Accounting.ViewInvoices', roles: ['Admin', 'Manager', 'Accountant'] },
  { key: 'Permissions.Accounting.DeleteInvoice', module: 'Accounting', moduleDisplayName: 'Kế toán', displayName: 'Xoá/huỷ hoá đơn', type: 'Delete', dependsOn: 'Permissions.Accounting.ViewInvoices', roles: ['Admin', 'Accountant'] },
  { key: 'Permissions.Accounting.ManageInvoices', module: 'Accounting', moduleDisplayName: 'Kế toán', displayName: 'Phát hành hoá đơn điện tử', type: 'Manage', dependsOn: 'Permissions.Accounting.ViewInvoices', roles: ['Admin', 'Manager', 'Accountant'] },
  { key: 'Permissions.Accounting.ApproveCredit', module: 'Accounting', moduleDisplayName: 'Kế toán', displayName: 'Duyệt hạn mức công nợ', type: 'Approve', dependsOn: 'Permissions.Accounting.ViewInvoices', roles: ['Admin', 'Accountant'] },
  { key: 'Permissions.Accounting.ManageDebt', module: 'Accounting', moduleDisplayName: 'Kế toán', displayName: 'Quản lý công nợ', type: 'Manage', dependsOn: 'Permissions.Accounting.ViewInvoices', roles: ['Admin', 'Manager', 'Accountant'] },
  { key: 'Permissions.Accounting.ManageExpense', module: 'Accounting', moduleDisplayName: 'Kế toán', displayName: 'Quản lý chi phí', type: 'Manage', dependsOn: 'Permissions.Accounting.ViewInvoices', roles: ['Admin', 'Manager', 'Accountant'] },
  { key: 'Permissions.Accounting.ViewReports', module: 'Accounting', moduleDisplayName: 'Kế toán', displayName: 'Xem báo cáo kế toán', type: 'View', dependsOn: 'Permissions.Accounting.ViewInvoices', roles: ['Admin', 'Manager', 'Accountant'] },
  { key: 'Permissions.Accounting.Export', module: 'Accounting', moduleDisplayName: 'Kế toán', displayName: 'Xuất báo cáo tài chính', type: 'Export', dependsOn: 'Permissions.Accounting.ViewInvoices', roles: ['Admin', 'Manager', 'Accountant'] },
  { key: 'Permissions.HR.ViewEmployees', module: 'HR', moduleDisplayName: 'Nhân sự', displayName: 'Xem hồ sơ nhân viên', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Accountant', 'HR'] },
  { key: 'Permissions.HR.ManageEmployees', module: 'HR', moduleDisplayName: 'Nhân sự', displayName: 'Quản lý hồ sơ, hợp đồng nhân viên', type: 'Manage', dependsOn: 'Permissions.HR.ViewEmployees', roles: ['Admin', 'Manager', 'HR'] },
  { key: 'Permissions.HR.ViewAttendance', module: 'HR', moduleDisplayName: 'Nhân sự', displayName: 'Xem chấm công', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'HR'] },
  { key: 'Permissions.HR.ManageAttendance', module: 'HR', moduleDisplayName: 'Nhân sự', displayName: 'Quản lý chấm công, ca làm', type: 'Manage', dependsOn: 'Permissions.HR.ViewAttendance', roles: ['Admin', 'Manager', 'HR'] },
  { key: 'Permissions.HR.ApproveLeave', module: 'HR', moduleDisplayName: 'Nhân sự', displayName: 'Duyệt nghỉ phép, tăng ca', type: 'Approve', dependsOn: 'Permissions.HR.ViewAttendance', roles: ['Admin', 'Manager', 'HR'] },
  { key: 'Permissions.HR.ViewPayroll', module: 'HR', moduleDisplayName: 'Nhân sự', displayName: 'Xem bảng lương', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Accountant', 'HR'] },
  { key: 'Permissions.HR.ManagePayroll', module: 'HR', moduleDisplayName: 'Nhân sự', displayName: 'Tính và chốt bảng lương', type: 'Manage', dependsOn: 'Permissions.HR.ViewPayroll', roles: ['Admin', 'Manager', 'Accountant', 'HR'] },
  { key: 'Permissions.HR.ManageStatutoryParameters', module: 'HR', moduleDisplayName: 'Nhân sự', displayName: 'Sửa tham số lương/thuế/bảo hiểm theo luật', type: 'Manage', dependsOn: 'Permissions.HR.ViewPayroll', roles: ['Admin', 'Accountant'] },
  { key: 'Permissions.Users.View', module: 'Users', moduleDisplayName: 'Người dùng', displayName: 'Xem danh sách tài khoản', type: 'View', dependsOn: null, roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Users.Create', module: 'Users', moduleDisplayName: 'Người dùng', displayName: 'Tạo tài khoản mới', type: 'Create', dependsOn: 'Permissions.Users.View', roles: ['Admin'] },
  { key: 'Permissions.Users.Edit', module: 'Users', moduleDisplayName: 'Người dùng', displayName: 'Sửa thông tin tài khoản', type: 'Edit', dependsOn: 'Permissions.Users.View', roles: ['Admin', 'Manager'] },
  { key: 'Permissions.Users.Delete', module: 'Users', moduleDisplayName: 'Người dùng', displayName: 'Khoá/xoá tài khoản', type: 'Delete', dependsOn: 'Permissions.Users.View', roles: ['Admin'] },
  { key: 'Permissions.Users.ManageRoles', module: 'Users', moduleDisplayName: 'Người dùng', displayName: 'Gán vai trò cho tài khoản', type: 'Manage', dependsOn: 'Permissions.Users.View', roles: ['Admin'] },
  { key: 'Permissions.Roles.View', module: 'Roles', moduleDisplayName: 'Vai trò', displayName: 'Xem vai trò và ma trận quyền', type: 'View', dependsOn: null, roles: ['Admin'] },
  { key: 'Permissions.Roles.Create', module: 'Roles', moduleDisplayName: 'Vai trò', displayName: 'Tạo vai trò mới', type: 'Create', dependsOn: 'Permissions.Roles.View', roles: ['Admin'] },
  { key: 'Permissions.Roles.Edit', module: 'Roles', moduleDisplayName: 'Vai trò', displayName: 'Sửa quyền của vai trò', type: 'Edit', dependsOn: 'Permissions.Roles.View', roles: ['Admin'] },
  { key: 'Permissions.Roles.Delete', module: 'Roles', moduleDisplayName: 'Vai trò', displayName: 'Xoá vai trò', type: 'Delete', dependsOn: 'Permissions.Roles.View', roles: ['Admin'] },
  { key: 'Permissions.Reporting.ViewSales', module: 'Reporting', moduleDisplayName: 'Báo cáo', displayName: 'Xem báo cáo bán hàng', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Sale', 'Accountant', 'Marketing'] },
  { key: 'Permissions.Reporting.ViewInventory', module: 'Reporting', moduleDisplayName: 'Báo cáo', displayName: 'Xem báo cáo kho', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'InventoryStaff', 'Accountant'] },
  { key: 'Permissions.Reporting.ViewFinancial', module: 'Reporting', moduleDisplayName: 'Báo cáo', displayName: 'Xem báo cáo tài chính', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Accountant'] },
  { key: 'Permissions.Reporting.ViewRepair', module: 'Reporting', moduleDisplayName: 'Báo cáo', displayName: 'Xem báo cáo sửa chữa', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'TechnicianInShop'] },
  { key: 'Permissions.Reporting.ViewHR', module: 'Reporting', moduleDisplayName: 'Báo cáo', displayName: 'Xem báo cáo nhân sự', type: 'View', dependsOn: null, roles: ['Admin', 'Manager', 'Accountant', 'HR'] },
  { key: 'Permissions.Reporting.ExportReports', module: 'Reporting', moduleDisplayName: 'Báo cáo', displayName: 'Xuất báo cáo ra file', type: 'Export', dependsOn: null, roles: ['Admin', 'Manager', 'Accountant'] },
  { key: 'Permissions.System.ViewConfig', module: 'System', moduleDisplayName: 'Hệ thống', displayName: 'Xem cấu hình hệ thống', type: 'View', dependsOn: null, roles: ['Admin', 'Manager'] },
  { key: 'Permissions.System.ManageConfig', module: 'System', moduleDisplayName: 'Hệ thống', displayName: 'Thay đổi cấu hình hệ thống', type: 'Manage', dependsOn: 'Permissions.System.ViewConfig', roles: ['Admin'] },
  { key: 'Permissions.System.ViewLogs', module: 'System', moduleDisplayName: 'Hệ thống', displayName: 'Xem nhật ký hệ thống', type: 'View', dependsOn: null, roles: ['Admin'] },
  { key: 'Permissions.System.ManageLogs', module: 'System', moduleDisplayName: 'Hệ thống', displayName: 'Xoá/xuất nhật ký hệ thống', type: 'Manage', dependsOn: 'Permissions.System.ViewLogs', roles: ['Admin'] },
  { key: 'Permissions.System.ManageBackups', module: 'System', moduleDisplayName: 'Hệ thống', displayName: 'Sao lưu và phục hồi dữ liệu', type: 'Manage', dependsOn: 'Permissions.System.ViewConfig', roles: ['Admin'] },
];

