using BuildingBlocks.Spreadsheet;
using ClosedXML.Excel;

namespace Catalog.Application.BulkOps;

/// <summary>
/// Adds the `DanhMuc` lookup sheet (Architecture: "valid categories and brands generated from the
/// database as data validation") on top of what `ExcelImportPipeline.BuildTemplate` produces.
/// Re-opens the generated bytes with ClosedXML rather than duplicating template generation - the
/// package is already a transitive dependency via the `BuildingBlocks` project reference (same
/// 0.104.1 pinned there), so this needs no change to `Catalog.csproj`.
/// </summary>
public static class ProductImportWorkbookExtras
{
    public static byte[] BuildTemplateWithLookup(ExcelImportPipeline<ProductImportRow> pipeline, CategoryBrandMatcher lookup)
    {
        var templateBytes = pipeline.BuildTemplate();
        using var stream = new MemoryStream(templateBytes);
        using var workbook = new XLWorkbook(stream);

        var lookupSheet = workbook.Worksheets.Add("DanhMuc");
        lookupSheet.Cell(1, 1).Value = "Danh mục hợp lệ";
        lookupSheet.Cell(1, 1).Style.Font.Bold = true;
        lookupSheet.Cell(1, 2).Value = "Thương hiệu hợp lệ";
        lookupSheet.Cell(1, 2).Style.Font.Bold = true;

        var categories = lookup.CategoryNames;
        var brands = lookup.BrandNames;
        for (var i = 0; i < categories.Count; i++) lookupSheet.Cell(i + 2, 1).Value = categories[i];
        for (var i = 0; i < brands.Count; i++) lookupSheet.Cell(i + 2, 2).Value = brands[i];
        lookupSheet.Column(1).Width = 40;
        lookupSheet.Column(2).Width = 30;

        var dataSheet = workbook.Worksheets.Worksheet(1);
        const int firstDataRow = 3; // hàng 1 = tiêu đề, hàng 2 = gợi ý (ExcelImportPipeline.BuildTemplate)
        const int lastDataRow = 5000; // khớp ExcelImportPipeline.DefaultMaxRows
        if (categories.Count > 0)
        {
            var sourceRange = lookupSheet.Range(2, 1, categories.Count + 1, 1);
            dataSheet.Range(firstDataRow, 3, lastDataRow, 3).SetDataValidation().List(sourceRange); // "Danh mục" = cột C
        }
        if (brands.Count > 0)
        {
            var sourceRange = lookupSheet.Range(2, 2, brands.Count + 1, 2);
            dataSheet.Range(firstDataRow, 4, lastDataRow, 4).SetDataValidation().List(sourceRange); // "Thương hiệu" = cột D
        }

        using var output = new MemoryStream();
        workbook.SaveAs(output);
        return output.ToArray();
    }
}
