<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.6.6" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.6" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Services/Accounting/Accounting.csproj" />
    <ProjectReference Include="../../Services/Catalog/Catalog.csproj" />
    <ProjectReference Include="../../Services/Sales/Sales.csproj" />
    <ProjectReference Include="../../Services/Inventory/Inventory.csproj" />
    <ProjectReference Include="../../Services/HR/HR.csproj" />
    <ProjectReference Include="../../Services/Warranty/Warranty.csproj" />
  </ItemGroup>
</Project>
